# hyprlang noerror false
# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

ecosystem{
  no_update_news = true
}

monitor=HDMI-A-1,2560x1440@75,0x0,1
