# hyprlang noerror false
# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

workspace = special:special, on-created-empty:kitty
workspace = 2,on-created-empty:gtk-launch feishu
# workspace = 3,on-created-empty:/home/present/.local/share/JetBrains/Toolbox/apps/android-studio/bin/studio
workspace = 7,on-created-empty:gtk-launch io.element.Element

windowrulev = match:title ^(图片查看器)$, class ^(QQ)$, float on# Imaagerviewer-qq
windowrulev = match:title ^(磁力链接)$, class ^(qbittorrent)$, float on# qbittorrent
windowrulev = match:class (scrcpy), tile on # scrcpy
